### ISSUE TITLE
Job Description for Director, Global Marketing

### ISSUE THREAD

**Issue by nrmehta** [Falkonry/hr#6]
### Ideal Candidate
The ideal candidate loves story telling and is data-driven, self-motivated and versatile... and gets stuff done. The candidate should have experience launching new products into global markets and preferably has worked with Fortune 2000 enterprises.

Your customers are transforming themselves digitally and they should easily find Falkonry and establish a preference for Falkonry. You are skilled in executing against a business plan to meet or exceed monthly and quarterly marketing targets. 

### Responsibilities
You will be reporting to the SVP of Marketing and working with members of the marketing, sales, products, and customer success teams. Your work will include:

- Evangelizing Falkonry's products, impact on organizations, and industries
- Building and managing a rich content/editorial calendar that attracts a qualified audience to our and partner-owned properties (including blog posts, whitepapers, ebooks, reports, webinars, infographics, etc.).
- Optimizing our marketing automation and lead nurturing processes through email, content, and social channels.
- Attracting site traffic, converting that traffic into new leads for the business, and nurturing those leads to close into customers
- Partnering with Product teams and ecosystem partners to promote predictive analytics products & solutions
- Establishing closed-loop analytics with sales to understand how our inbound marketing activity turns into customers, and continually refine our process to convert customers.
- Experience:
- Excellent communicator and creative thinker, with an ability to use data to inform all decisions
- Proficiency in marketing automation, content distribution technologies, and Web/search tools
- Enterprise sales process and global marketing

### Qualifications:

- BA/BS degree 
- End-to-end experience with launch strategy, content design, marketing automation, and reporting

**Comment by nrmehta** [comment]
@sanketamberkar - please review this job description and suggest any changes in a separate comment. When ready, @pratibha-mehta should update the current job post.

**Comment by pratibha-mehta** [comment]
@sanketamberkar - Please let me know when you are done reviewing this. Thanks!

**Comment by sanketamberkar** [comment]
Hi @pratibha-mehta, please see the attached updated job description for the [Director of Global Marketing role](https://docs.google.com/document/d/1r4o5KxRK4jiZ_54zIEXa4CGm2UFrQq9qXJhOF6Kk07M/edit#).

Please note the job title on the Greenhouse posting (Content Marketing Director) is incorrect

**Comment by pratibha-mehta** [comment]
@sanketamberkar - The online posting has the correct title. Internal job name which only appears in Greenhouse has "Content Marketing Director" title, which I have updated. All good.

**Comment by pratibha-mehta** [comment]
@sanketamberkar - Updated the JD. Please check it out here- https://falkonry.com/careers/?gh_jid=4118209002

**Comment by sanketamberkar** [comment]
Thanks Pratibha. It looks good.
-Sanket

Sanket Amberkar | SVP of Marketing & Partnerships

Tel: +1408.529.3951 | www.falkonry.com

**Comment by nrmehta** [comment]
Approved
