### ISSUE TITLE
Review/Approve JD for Inside Sales Executive position

### ISSUE THREAD

**Issue by pratibha-mehta** [Falkonry/hr#7]
Once its been approved Pratibha updates the JD in Greenhouse. Here is the GD link for JD-

https://docs.google.com/document/d/1iyKFkststRUHGSCJYrYFdOA0wLwZfik1Dhw-u_sUPtE/edit

**Comment by pratibha-mehta** [comment]
@nrmehta @sanketamberkar

**Comment by sanketamberkar** [comment]
Approved.

**Comment by pratibha-mehta** [comment]
@nrmehta - Waiting on your approval. Thanks!
https://docs.google.com/document/d/1OH0_ktX_qDdPuWRXuXblX4Ar8x_mq6H5iHv0J_HSh-s/edit

**Comment by nrmehta** [comment]
Approved.
